id: P000820
initial_creation_type: ebook
source_metadata:
  title: Test
  subtitle: Test
  authors:
  - Test
  collection: Test
  publisher: Test
  id: SKU-01
  cover: tmpdk4vxik7.jpg
  credit: tmpxclnnjdy.jpg
